title: Github pages Tutorial Page
author: Simon Sokyrko
email: simonsokyrko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the Github page created for the tutorial in the creation of Github pages

# social links
github_username:  simms0 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
